### ISSUE TITLE
Does TextToolsPro support Choice type ?

### ISSUE THREAD

**Issue by onirix** [lochidev/Expandroid#20]
I’d like to add a list of values when triggering but I can’t.

https://espanso.org/docs/matches/extensions/#choice-extension

Where I am wrong ?

![IMG_20240722_101907](https://github.com/user-attachments/assets/211d611e-e2b8-4564-b2ee-fdd2c28220d2)
![Screenshot_2024-07-22-10-18-33-82_ecfe3044ac714fe7d20db5cea2ce4b21](https://github.com/user-attachments/assets/3e96c4f1-9cc8-4e46-a1e7-b47205ae60ac)

**Comment by lochidev** [comment]
No there is no support yet. Cause that requires a floating window and that's a lot to figure out. I'm hoping to add form support soon and with that this too. Just haven't had free time yet to finish it.

**Comment by lochidev** [comment]
https://github.com/lochidev/Expandroid/releases/tag/v7.0.0

**Comment by onirix** [comment]
Can you make an example to use this new feature?
I can't display anything else that {{output}} 😅

**Comment by lochidev** [comment]
https://github.com/lochidev/Expandroid/blob/main/examples/config.yml
