### ISSUE TITLE
Add Button Not Working

### ISSUE THREAD

**Issue by DeMoN100** [lochidev/Expandroid#30]
Using a Moto G Stylus 5G 2023 Android 13 the add button does not work & I cannot add other expressions for text replacement.

**Comment by lochidev** [comment]
Using the pen only or with touch too?  

> I cannot add other expressions for text replacement.

Please elaborate. I don't have pens so I don't know if I can fix this.

**Comment by DeMoN100** [comment]
> Using the pen only or with touch too?
> 
> > I cannot add other expressions for text replacement.
> 
> Please elaborate.
> 
> I don't have a stylus pen so I don't know if I can fix this.

With touch I did not even think to try it with the stylus pen which I imagine would be the same result.

**Comment by DeMoN100** [comment]
> Hey. Could you maybe post a recorded video? Because I can't replicate this, the add button has worked everywhere I've tested.

Now that I went to take a video the add button is now working. I am not sure why all I did between then & now was redownloaded the app. Maybe that was all it needed.

Thanks!
