### ISSUE TITLE
Does Not Work on A53 5G

### ISSUE THREAD

**Issue by DeMoN100** [lochidev/Expandroid#32]
I tried this on a Samsung A53 5G & it does not work at all in any app. Yes it has accessibility permissions.

Here is a video.
https://github.com/user-attachments/assets/b59a2663-5852-4da2-bba7-b46ed2583087

**Comment by lochidev** [comment]
Hmm, there are somethings we can try.

1. Reinstall the app. Try turning on accessibility service on and off. Before you do that make sure your config is saved, by clicking on the save button.
2. Share your config with me if you can, it maybe causing some bugs which I could catch if I can replicate this.
3. Try force quitting the app.
4. Turn off battery optimization for the app.

I did test on element messenger and it works for me.

**Comment by DeMoN100** [comment]
Okay after reinstalling it's working now. Not sure what happened the first time everything was correct. I had even tried at first switching it on & off but it wasn't working in any app. Now it is after reinstall.
