### ISSUE TITLE
Feat Requests: Date Formats

### ISSUE THREAD

**Issue by DeMoN100** [lochidev/Expandroid#33]
When using the templates that display dates it is displayed as day month year. I know in other parts of the world that's their format. Our format is month day year so it looks wrong when i'm sending these out to people. 

When tapping on the date button there should be options for display such as month/day/year, day/month/year, & year-day-month.

**Comment by lochidev** [comment]
I am pretty sure you can accomplish what you need already by making a manual variable. To do so, check out the "advanced options for espanso users" section and fill out a custom variable. DOCS: https://espanso.org/docs/matches/extensions/#date-extension

**Comment by lochidev** [comment]
See: https://github.com/lochidev/Expandroid/blob/main/examples/config.yml

**Comment by DeMoN100** [comment]
> I am pretty sure you can accomplish what you need already by making a manual variable. To do so, check out the "advanced options for espanso users" section and fill out a custom variable. DOCS: https://espanso.org/docs/matches/extensions/#date-extension (Note: localized dates are not supported yet, mentioned in the docs but this app doesn't support that yet, maybe I'll add it in the future)

It would be greatly appreciated if you could implement it. As your format was implemented naturally everyone elses should be as well. There shouldn't be extra steps & manual configurations needed just for me to switch the format to what my country runs on. I appreciate you sending me the links to show me how I can do it with esprano I will use this as a temporary solution till the update comes implementing it.

**Comment by lochidev** [comment]
Hi. Sorry man, I can't implement everything everyone wants. This app takes tons of time to develop, and I'm a full-time engineering undergrad.  I contribute what I think matters most for the time I'm spending. Anyone is welcome to contribute, if you can help improve the project, I'll be more than happy to help coding & look at pull requests. I hope you can understand.

And also there's this slight fact that the app is directed towards existing espanso users. I'll be closing the issue now. Feel free to reopen if run into some issues.

**Comment by DeMoN100** [comment]
Thanks for letting me know keep in mind when developing any app any format expressional outputs should always be u ready for anyones date & time zones as we all know everyone has a different time & date format. Like languages how they have to be prepared for people to read dnt is part of that.

Of course you can't put what everyone wants & there is a standard must haves natural expectancy. Then theres the features people want for convenince, improvements, quality enchancements, & etc. Then last theres the optional not nescessairy but would be nice to have if requested list.

I'm not a coder myself so I can't begin to implement but I can only hope in the future it will be there in the next update.

**Comment by lochidev** [comment]
Switched to US style dates in v7.1.0
